name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: pm2 delete all
      - run : npm run scale
      - run: npm run build --if-present

      # Add the new step to create the environment file
      - name: Create env file
        run: |
          touch .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
          echo MAIL=${{ secrets.MAIL }} >> .env
          echo PASS=${{ secrets.PASS }} >> .env
          echo AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo BUCKET_NAME=${{ secrets.BUCKET_NAME }} >> .env
          echo AWS_REGION=${{ secrets.AWS_REGION }} >> .env
          echo PORT=8080 >> .env
          cat .env
